# Generated by Django 5.0.7 on 2024-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referal',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='referal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
    ]
