# Generated by Django 5.0.7 on 2024-10-18 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 17, 6, 51, 207397, tzinfo=datetime.timezone.utc)),
        ),
    ]
