# Generated by Django 5.0.7 on 2024-10-27 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_userprofile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 10, 3, 51, 197431, tzinfo=datetime.timezone.utc)),
        ),
    ]
